name: Kaggle API Data Pipeline

on:
  workflow_dispatch:

jobs:
  run-kaggle-api-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install papermill

      - name: Run Kaggle API Extract Notebook
        run: |
          papermill notebooks/MLBPay_API_Extract_Load_Raw.ipynb notebooks/MLBPay_API_Extract_Load_Raw_output.ipynb
